name: Feature

on:
  pull_request:
    branches:
      - main

jobs:
  build_feature:
    name: Build feature
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            name: linux
          - os: macos-latest
            name: mac
          - os: windows-latest
            name: win

    steps:
      - name: Setup APT
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update

          sudo apt-get install -y \
          devscripts \
          libxcb-cursor-dev \
          libxcb-keysyms1-dev \
          libxcb-util-dev \
          libxkbcommon-dev \
          libxkbcommon-x11-dev \
          ninja-build \
          libcogl-pango-dev \
          libpangoft2-1.0-0 \
          libpango-1.0-0 \
          libgtk-3-dev \
          libgtkmm-3.0-dev \
          xcb



      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build binary
        run: |
          cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Debug -DSST_JUCEGUI_BUILD_EXAMPLES=TRUE -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
          cmake --build ./build --config Debug
